// Code generated by hertz generator.

package checkout

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/py/biz-demo/gomall/app/frontend/middlware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middlware.Auth()}
}

func _checkoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkout0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutwaitingMw() []app.HandlerFunc {
	// your code...
	return nil
}
