apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: "product:v1.1.1"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: "product-config"
          mountPath: /opt/gomall/product/conf/dev
        env:
        - name: GO_ENV
          value: "dev"
        - name: MYSQL_HOST
          value: "mysql-svc"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-paasword
              key: password
      volumes:
      - name: "product-config"
        configMap:
          name: gomall-config
          items:
          - key: product-app-config
            path: conf.yaml
            
--- # frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:v1.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8090
        volumeMounts:
        - name: "frontend-config"
          mountPath: /opt/gomall/frontend/conf/dev
        env:
        - name: GO_ENV
          value: "dev"
        - name: SESSION_SECRET
          value: "WDGCYESAAA"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "jaeger-svc:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
      volumes:
      - name: "frontend-config"
        configMap:
          name: gomall-config
          items:
          - key: frontend-app-config
            path: conf.yaml    

--- #cart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: "cart:v1.1.1"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: "cart-config"
            mountPath: /opt/gomall/cart/conf/dev
        env:
          - name: GO_ENV
            value: "dev"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "jaeger-svc:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
          - name: MYSQL_HOST
            value: "mysql-svc"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-paasword
                key: password
      volumes:
      - name: "cart-config"
        configMap:
          name: gomall-config
          items:
          - key: cart-app-config
            path: conf.yaml            


--- #checkout
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: checkout:v1.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: "checkout-config"
            mountPath: /opt/gomall/checkout/conf/dev
        env:
          - name: GO_ENV
            value: "dev"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "jaeger-svc:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"            
      volumes:
      - name: "checkout-config"
        configMap:
          name: gomall-config
          items:
          - key: checkout-app-config
            path: conf.yaml            

--- #email
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
spec:
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: email:v1.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: "email-config"
            mountPath: /opt/gomall/email/conf/dev
        env:
          - name: GO_ENV
            value: "dev"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "jaeger-svc:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"            
      volumes:
      - name: "email-config"
        configMap:
          name: gomall-config
          items:
          - key: email-app-config
            path: conf.yaml            

--- #order
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: order:v1.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: "order-config"
            mountPath: /opt/gomall/order/conf/dev
        env:
          - name: GO_ENV
            value: "dev"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "jaeger-svc:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"            
          - name: MYSQL_HOST
            value: "mysql-svc"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-paasword
                key: password
      volumes:
      - name: "order-config"
        configMap:
          name: gomall-config
          items:
          - key: order-app-config
            path: conf.yaml            
--- #payment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: payment:v1.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: "payment-config"
            mountPath: /opt/gomall/payment/conf/dev
        env:
          - name: GO_ENV
            value: "dev"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "jaeger-svc:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"            
          - name: MYSQL_HOST
            value: "mysql-svc"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-paasword
                key: password
      volumes:
      - name: "payment-config"
        configMap:
          name: gomall-config
          items:
          - key: payment-app-config
            path: conf.yaml            
--- #user
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user:v1.1.1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - name: "user-config"
            mountPath: /opt/gomall/user/conf/dev
        env:
          - name: GO_ENV
            value: "dev"
          - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: "jaeger-svc:4317"
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: "true"
          - name: MYSQL_HOST
            value: "mysql-svc"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-paasword
                key: password
      volumes:
      - name: "user-config"
        configMap:
          name: gomall-config
          items:
          - key: user-app-config
            path: conf.yaml            


--- # config
apiVersion: v1
kind: ConfigMap
metadata:
  name: gomall-config
data:
  product-app-config: |
      kitex:
        service: "product"
        address: ":8889"
        log_level: info
        log_file_name: "log/kitex.log"
        log_max_size: 10
        log_max_age: 3
        log_max_backups: 50
        metrics_port: ":9996"

      registry:
        registry_address:
          - consul-svc:8500
        username: ""
        password: ""

      mysql:
        dsn: "%s:%s@tcp(%s:3306)/product?charset=utf8mb4&parseTime=True&loc=Local"


      redis:
        address: "redis-svc:6379"
        username: ""
        password: ""
        db: 0
  frontend-app-config: |
    hertz:
      service: "frontend"
      address: ":8090"
      enable_pprof: true
      enable_gzip: true
      enable_access_log: true
      log_level: info
      log_file_name: "log/hertz.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      registry_addr: "consul-svc:8500"
      metrics_port: ":9998"

    mysql:
      dsn: "%s:%s@tcp(%s:3306)/user?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis-svc:6379"
      username: ""
      password: ""
      db: 0
  cart-app-config: |
    kitex:
      service: "cart"
      address: ":8883"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      metrics_port: ":9993"

    registry:
      registry_address:
        - consul-svc:8500
      username: ""
      password: ""

    mysql:
      dsn: "%s:%s@tcp(%s:3306)/cart?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis-svc:6379"
      username: ""
      password: ""
      db: 0
  checkout-app-config: |
    kitex:
      service: "checkout"
      address: ":8885"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      metrics_port: ":9992"

    registry:
      registry_address:
        - consul-svc:8500
      username: ""
      password: ""

    mysql:
      dsn: "%s:%s@tcp(%s:3306)/checkout?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis-svc:6379"
      username: ""
      password: ""
      db: 0
  email-app-config: |
    kitex:
      service: "email"
      address: ":8887"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      metrics_port: ":9994"

    registry:
      registry_address:
        - consul-svc:8500
      username: ""
      password: ""

    mysql:
      dsn: "gorm:gorm@tcp(127.0.0.1:3306)/gorm?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis:6379"
      username: ""
      password: ""
      db: 0

    nats:
      address: "nats-svc:4222"
  order-app-config: |
    kitex:
      service: "order"
      address: ":8886"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      metrics_port: ":9991"

    registry:
      registry_address:
        - consul-svc:8500
      username: ""
      password: ""

    mysql:
      dsn: "%s:%s@tcp(%s:3306)/order?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis-svc:6379"
      username: ""
      password: ""
      db: 0
  payment-app-config: |
    kitex:
      service: "payment"
      address: ":8884"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      metric_port: ":9995"

    registry:
      registry_address:
        - consul-svc:8500
      username: ""
      password: ""

    mysql:
      dsn: "%s:%s@tcp(%s:3306)/payment?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis-svc:6379"
      username: ""
      password: ""
      db: 0
  user-app-config: |
    kitex:
      service: "user"
      address: ":8888"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50
      metrics_port: ":9997"

    registry:
      registry_address:
        - "consul-svc:8500"
      username: ""
      password: ""

    mysql:
      dsn: "%s:%s@tcp(%s:3306)/user?charset=utf8mb4&parseTime=True&loc=Local"

    redis:
      address: "redis-svc:6379"
      username: ""
      password: "%s"
      db: 0


