kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gomall-dev
nodes:
- role: control-plane
  image: kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/ini
    containerPath: /opt/gomall/db/sql/ini
  - hostPath: ./deploy/config
    containerPath: /opt/gomall/deploy/config
  extraPortMappings:
    - containerPort: 8090
      hostPort: 8090
      protocol: TCP
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP

- role: worker
  image: kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/ini
    containerPath: /opt/gomall/db/sql/ini
  - hostPath: ./deploy/config
    containerPath: /opt/gomall/deploy/config

# image for China: registry.cn-hangzhou.aliyuncs.com/kindest/node:v1.30.0
- role: worker
  image: kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/ini
    containerPath: /opt/gomall/db/sql/ini
  - hostPath: ./deploy/config
    containerPath: /opt/gomall/deploy/config